apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: scp-rest-svr
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30180
    name: http
    protocol: TCP
  selector:
    app: scp-rest-svr
