# permissions for end users to view managedoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedoperator-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - managedoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - managedoperators/status
  verbs:
  - get
