# permissions for end users to edit scpclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scpcluster-editor-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - scpclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - scpclusters/status
  verbs:
  - get
