apiVersion: "webapp.my.domain/v1"
kind: "ManagedOperator"
metadata:
  name: "managedoperator-sample-2"
spec:
  # Add fields here
  name: "postgres"
  crdname: "postgres.sql.tanzu.vmware.com"
  servicelabel: ""
  servicetype: "ClusterIP"
  version: "v1.0.0"
  crinputs:
  - controlName: DB Name
    controlType: text
    valueType: text
    placeholder: Enter DB name
    validators:
      required: true
      minlength: 5
    crpath: spec.Pg.Config.Dbname
  - controlName: DB Username
    controlType: text
    valueType: text
    placeholder: Enter DB username
    validators:
      required: true
      minlength: 5
    crpath: spec.Pg.Config.Username
  - controlName: Memory
    placeholder: Enter Memory
    valueType: number
    controlType: text
    validators:
      required: true
      minlength: 7
      maxlength: 10
    crpath: spec.Memory
  - controlName: CPU
    valueType: number
    placeholder: Enter cpu
    controlType: number
    validators:
      required: true
    crpath: spec.Cpu
  - controlName: Storage
    placeholder: Select storage
    valueType: text
    controlType: select
    options:
      - optionName: 100 GB
        value: 100GB
      - optionName: 200 GB
        value: 200GB
    validators:
      required: true
    crpath: spec.StorageSize
  - controlName: High Availability
    placeholder: High Availability
    valueType: boolean
    controlType: checkbox
    options:
      - optionName: Enable HA
        value: haenabled
    validators:
      required: true
    crpath: spec.HighAvailability
  croutputs:
  - controlName: Status
    controlType: text
    currentValue: ""
    valueType: text
    crpath: "status.phase"  