apiVersion: "webapp.my.domain/v1"
kind: "ManagedOperator"
metadata:
  name: "managedoperator-sample"
spec:
  # Add fields here
  name: "etcd"
  crdname: "etcdclusters.etcd.database.coreos.com"
  servicelabel: "app=etcd"
  servicetype: "ClusterIP"
  version: "v0.9.4"
  crinputs:
  - controlName: Name
    controlType: text
    valueType: text
    placeholder: Service name
    validators:
      required: true
      minlength: 5
    crpath: metadata.name
  - controlName: Replicas
    placeholder: Number of Pods
    valueType: number
    controlType: text
    validators:
      required: true
      minlength: 1
      maxlength: 3
    crpath: spec.size
  - controlName: Version
    placeholder: Select DB Version
    valueType: text
    controlType: select
    options:
      - optionName: 3.1.10
        value: 3.1.10
    validators:
      required: true
    crpath: spec.version
  croutputs:
  - controlName: svcname
    controlType: text
    currentValue: ""
    valueType: text
    crpath: "status.serviceName"
  - controlName: svcport
    controlType: text
    currentValue: ""
    valueType: number
    crpath: "status.clientPort"
  - controlName: svcsize
    controlType: text
    currentValue: ""
    valueType: number
    crpath: "status.size"
  - controlName: svcphase
    controlType: text
    currentValue: ""
    valueType: text
    crpath: "status.phase"
