apiVersion: "webapp.my.domain/v1"
kind: "ManagedOperator"
metadata:
  name: "managedoperator-sample"
spec:
  # Add fields here
  name: "etcd"
  deploymentname: "EtcdCluster"
  servicelabel: "app=etcd"
  servicetype: "ClusterIP"
  version: "quay.io/coreos/etcd-operator:v0.9.4"
  deploymentinputs:
  - controlName: Name
    controlType: text
    valueType: text
    placeholder: Service name
    validators:
      required: true
      minlength: 5
  - controlName: Replicas
    placeholder: Number of Pods
    valueType: text
    controlType: text
    validators:
      required: true
      minlength: 1
      maxlength: 3


